version: '3.7'

services:
  geolocation:
    build:
      context: .
    volumes:
      - "./:/var/www"
    env_file:
      - .env
    depends_on:
      - redis
      - kafka
    networks:
      - geo-network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - geo-network

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9091:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - geo-network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '63799:6379'
    networks:
      - geo-network

networks:
  geo-network:
      driver:
        bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
